Repository Team-RecruTe/RecruTe-Service, pull requests merged in 2023-10, with the labels that each got.

#34 Chore: 코드 컨벤션, 의존성 추가, gitignore 설정, mybatis config 설정
  hossi97/recrute/mvnw
  kihong1602/recrute/.gitignore
  kihong1602/recrute/.idea/compiler.xml
  kihong1602/recrute/.idea/dataSources.xml
  kihong1602/recrute/.idea/jarRepositories.xml
  kihong1602/recrute/.mvn/wrapper/maven-wrapper.jar
  kihong1602/recrute/pom.xml
  kihong1602/recrute/src/main/resources/config/mybatis-config.xml
Labels: chore

#73 회원가입 / 로그인 / 로그아웃 기능 구현
  jujuri/recrute/.classpath
  jujuri/recrute/.gitignore
  jujuri/recrute/.project
  jujuri/recrute/build/classes/com/juju/mybatis/config.xml
  jujuri/recrute/pom.xml
  jujuri/recrute/src/main/java/EmailTest.java
  jujuri/recrute/src/main/java/EmailTestServlet.java
  jujuri/recrute/src/main/java/com/juju/controller/exam/ExamAuthServlet.java
  jujuri/recrute/src/main/java/com/juju/controller/exam/ExamEmailSend.java
  jujuri/recrute/src/main/java/com/juju/controller/hire/ApplyProcess.java
  jujuri/recrute/src/main/java/com/juju/controller/hire/HireView.java
  jujuri/recrute/src/main/java/com/juju/controller/index/Index.java
  jujuri/recrute/src/main/java/com/juju/controller/member/EmailCheck.java
  jujuri/recrute/src/main/java/com/juju/controller/member/IdCheck.java
  jujuri/recrute/src/main/java/com/juju/controller/member/SignIn.java
  jujuri/recrute/src/main/java/com/juju/controller/member/SignInProcess.java
  jujuri/recrute/src/main/java/com/juju/controller/member/SignOut.java
  jujuri/recrute/src/main/java/com/juju/controller/member/SignUp.java
  jujuri/recrute/src/main/java/com/juju/controller/member/SignUpProcess.java
  jujuri/recrute/src/main/java/com/juju/dao/ApplicantDao.java
  jujuri/recrute/src/main/java/com/juju/dao/ExamDao.java
  jujuri/recrute/src/main/java/com/juju/dao/HireDao.java
  jujuri/recrute/src/main/java/com/juju/dao/MemberDao.java
  jujuri/recrute/src/main/java/com/juju/dto/ApplicantDto.java
  jujuri/recrute/src/main/java/com/juju/dto/ExamDto.java
  jujuri/recrute/src/main/java/com/juju/dto/HireDto.java
  jujuri/recrute/src/main/java/com/juju/dto/MemberDto.java
  jujuri/recrute/src/main/java/com/juju/mybatis/MybatisConnectionFactory.java
  jujuri/recrute/src/main/java/com/juju/mybatis/applicant.xml
  jujuri/recrute/src/main/java/com/juju/mybatis/config.xml
  jujuri/recrute/src/main/java/com/juju/mybatis/exam.xml
  jujuri/recrute/src/main/java/com/juju/mybatis/hire.xml
  jujuri/recrute/src/main/java/com/juju/mybatis/member.xml
  jujuri/recrute/src/main/java/com/juju/service/ApplicantService.java
  jujuri/recrute/src/main/java/com/juju/service/ExamService.java
  jujuri/recrute/src/main/java/com/juju/service/HireService.java
  jujuri/recrute/src/main/java/com/juju/service/MemberService.java
  jujuri/recrute/src/main/java/com/juju/util/CookieManager.java
  jujuri/recrute/src/main/java/com/juju/util/EmailManager.java
  jujuri/recrute/src/main/java/com/juju/util/MakeRandomCode.java
  jujuri/recrute/src/main/java/com/juju/util/ScriptWriter.java
  jujuri/recrute/src/main/webapp/WEB-INF/exam/authorization.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/exam/exam-view.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/hire/view.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/include/footer.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/include/header.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/index/index.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/member/email-check.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/member/id-check.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/member/login-complete.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/member/signin.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/member/signup.jsp
  jujuri/recrute/src/main/webapp/WEB-INF/web.xml
  jujuri/recrute/src/main/webapp/js/jquery-3.7.1.min.js
  jujuri/recrute/src/module-info.java
Labels: feature

#74 Feat: 로그인 / 로그아웃 기능 구현
  jujuri/recrute/.gitignore
  jujuri/recrute/pom.xml
  kihong1602/recrute/.idea/codeStyles/codeStyleConfig.xml
  kihong1602/recrute/.idea/saveactions_settings.xml
  kihong1602/recrute/src/main/java/com/blanc/recrute/HelloServlet.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/controller/IdCheckController.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/controller/SignInController.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/controller/SignOutController.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/controller/SignUpController.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dao/MemberDAO.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dao/MemberDAOImpl.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dto/Gender.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dto/IdCheckDTO.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dto/InvalidDTO.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dto/LoginDTO.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/dto/MemberDTO.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/service/MemberService.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/service/MemberServiceImpl.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/util/Authenticater.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/util/JsonUtil.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/member/view/ViewResolver.java
  kihong1602/recrute/src/main/java/com/blanc/recrute/mybatis/MybatisConnectionFactory.java
  kihong1602/recrute/src/main/resources/config/mybatis-config.xml
  kihong1602/recrute/src/main/resources/images/signup/congratulation.png
  kihong1602/recrute/src/main/resources/mapper/member.xml
  kihong1602/recrute/src/main/webapp/WEB-INF/layout/footer.jsp
  kihong1602/recrute/src/main/webapp/WEB-INF/layout/header.jsp
  kihong1602/recrute/src/main/webapp/WEB-INF/layout/main.jsp
  kihong1602/recrute/src/main/webapp/WEB-INF/member/login/signin-process.jsp
  kihong1602/recrute/src/main/webapp/WEB-INF/member/register/signup-process.jsp
  kihong1602/recrute/src/main/webapp/WEB-INF/member/register/signup.jsp
  kihong1602/recrute/src/main/webapp/css/layout.css
  kihong1602/recrute/src/main/webapp/index.jsp
  kihong1602/recrute/src/main/webapp/js/signIn.js
  kihong1602/recrute/src/main/webapp/js/signUp.js
Labels: feature, chore
